name: 'Fetch and Initialize'
description: 'Fetches and initializes the repository, then sets up Python.'

inputs:
  repository:
    description: 'The repository to check out'
    required: true
    default: 'S-Holstein/Ci_Test'
  dependency:
    description: 'The tool to use'
    required: true
  cmd_run:
    description: 'cmd'
    required: true



runs:

  using: 'composite'

  steps:
    - name: Checkout Repository
      run: |
        git init
        git remote add origin https://github.com/${{ inputs.repository }}.git
        git config core.sparseCheckout true
        
        echo "synced/" >> .git/info/sparse-checkout
        
        git pull origin main
      shell: bash # Specify the shell to use, e.g., bash


    - name: Test
      run: |
        echo "--------"
        ls -a Dummy
        echo "--------"
      shell: bash


    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ inputs.dependency }}
      shell: bash

    - name: Tool Run
      run: |
        ${{ inputs.cmd_run }}
      shell: bash




