name: 'Fetch and Initialize'
description: 'Fetches and initializes the repository, then sets up Python.'

inputs:
  repository:
    description: 'The repository to check out'
    required: true
    default: 'S-Holstein/Ci_Test'


runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      run: |
        git init
        git remote add origin https://github.com/${{ inputs.repository }}.git
        git config core.sparseCheckout true
        echo "synced/" >> .git/info/sparse-checkout
        git pull origin main

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"




